//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Allocat.WebApi.CustomService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
        "essEntities")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Allocat.WebApi.CustomService.BankAccount BankAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Allocat.WebApi.CustomService.CreditCard CardInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerPaymentProfileIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Allocat.WebApi.CustomService.AddressInfo HomeAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Allocat.WebApi.CustomService.AddressInfo OfficeAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Allocat.WebApi.CustomService.PaymentType PaymentTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Allocat.WebApi.CustomService.BankAccount BankAccount {
            get {
                return this.BankAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAccountField, value) != true)) {
                    this.BankAccountField = value;
                    this.RaisePropertyChanged("BankAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Allocat.WebApi.CustomService.CreditCard CardInfo {
            get {
                return this.CardInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.CardInfoField, value) != true)) {
                    this.CardInfoField = value;
                    this.RaisePropertyChanged("CardInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIdField, value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerPaymentProfileId {
            get {
                return this.CustomerPaymentProfileIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPaymentProfileIdField, value) != true)) {
                    this.CustomerPaymentProfileIdField = value;
                    this.RaisePropertyChanged("CustomerPaymentProfileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Allocat.WebApi.CustomService.AddressInfo HomeAddress {
            get {
                return this.HomeAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeAddressField, value) != true)) {
                    this.HomeAddressField = value;
                    this.RaisePropertyChanged("HomeAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Allocat.WebApi.CustomService.AddressInfo OfficeAddress {
            get {
                return this.OfficeAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficeAddressField, value) != true)) {
                    this.OfficeAddressField = value;
                    this.RaisePropertyChanged("OfficeAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Allocat.WebApi.CustomService.PaymentType PaymentType {
            get {
                return this.PaymentTypeField;
            }
            set {
                if ((this.PaymentTypeField.Equals(value) != true)) {
                    this.PaymentTypeField = value;
                    this.RaisePropertyChanged("PaymentType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankAccount", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
        "essEntities")]
    [System.SerializableAttribute()]
    public partial class BankAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ECheckTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameOnAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoutingNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountType {
            get {
                return this.AccountTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountTypeField, value) != true)) {
                    this.AccountTypeField = value;
                    this.RaisePropertyChanged("AccountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankAccountNumber {
            get {
                return this.BankAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAccountNumberField, value) != true)) {
                    this.BankAccountNumberField = value;
                    this.RaisePropertyChanged("BankAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ECheckType {
            get {
                return this.ECheckTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ECheckTypeField, value) != true)) {
                    this.ECheckTypeField = value;
                    this.RaisePropertyChanged("ECheckType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameOnAccount {
            get {
                return this.NameOnAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.NameOnAccountField, value) != true)) {
                    this.NameOnAccountField = value;
                    this.RaisePropertyChanged("NameOnAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoutingNumber {
            get {
                return this.RoutingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RoutingNumberField, value) != true)) {
                    this.RoutingNumberField = value;
                    this.RaisePropertyChanged("RoutingNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditCard", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
        "essEntities")]
    [System.SerializableAttribute()]
    public partial class CreditCard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditCardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreditCardTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpiryDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditCardNumber {
            get {
                return this.CreditCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditCardNumberField, value) != true)) {
                    this.CreditCardNumberField = value;
                    this.RaisePropertyChanged("CreditCardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreditCardType {
            get {
                return this.CreditCardTypeField;
            }
            set {
                if ((this.CreditCardTypeField.Equals(value) != true)) {
                    this.CreditCardTypeField = value;
                    this.RaisePropertyChanged("CreditCardType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpiryDate {
            get {
                return this.ExpiryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpiryDateField, value) != true)) {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressInfo", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
        "essEntities")]
    [System.SerializableAttribute()]
    public partial class AddressInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentType", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
        "essEntities")]
    public enum PaymentType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreditCard = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ECheck = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResCreateCustomerProfile", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
        "essEntities.ResponseEntities")]
    [System.SerializableAttribute()]
    public partial class ResCreateCustomerProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CustomerPaymentProfileIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerProfileIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CustomerShippingProfileIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RefIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Allocat.WebApi.CustomService.ResTransaction TransactionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] CustomerPaymentProfileIds {
            get {
                return this.CustomerPaymentProfileIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPaymentProfileIdsField, value) != true)) {
                    this.CustomerPaymentProfileIdsField = value;
                    this.RaisePropertyChanged("CustomerPaymentProfileIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerProfileId {
            get {
                return this.CustomerProfileIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerProfileIdField, value) != true)) {
                    this.CustomerProfileIdField = value;
                    this.RaisePropertyChanged("CustomerProfileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] CustomerShippingProfileIds {
            get {
                return this.CustomerShippingProfileIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerShippingProfileIdsField, value) != true)) {
                    this.CustomerShippingProfileIdsField = value;
                    this.RaisePropertyChanged("CustomerShippingProfileIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageCode {
            get {
                return this.MessageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageCodeField, value) != true)) {
                    this.MessageCodeField = value;
                    this.RaisePropertyChanged("MessageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefId {
            get {
                return this.RefIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RefIdField, value) != true)) {
                    this.RefIdField = value;
                    this.RaisePropertyChanged("RefId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionToken {
            get {
                return this.SessionTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionTokenField, value) != true)) {
                    this.SessionTokenField = value;
                    this.RaisePropertyChanged("SessionToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Allocat.WebApi.CustomService.ResTransaction Transaction {
            get {
                return this.TransactionField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionField, value) != true)) {
                    this.TransactionField = value;
                    this.RaisePropertyChanged("Transaction");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResTransaction", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
        "essEntities.ResponseEntities")]
    [System.SerializableAttribute()]
    public partial class ResTransaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthCode {
            get {
                return this.AuthCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthCodeField, value) != true)) {
                    this.AuthCodeField = value;
                    this.RaisePropertyChanged("AuthCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorText {
            get {
                return this.ErrorTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorTextField, value) != true)) {
                    this.ErrorTextField = value;
                    this.RaisePropertyChanged("ErrorText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageCode {
            get {
                return this.MessageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageCodeField, value) != true)) {
                    this.MessageCodeField = value;
                    this.RaisePropertyChanged("MessageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageDescription {
            get {
                return this.MessageDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageDescriptionField, value) != true)) {
                    this.MessageDescriptionField = value;
                    this.RaisePropertyChanged("MessageDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIdField, value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomService.AllocatCustomService")]
    public interface AllocatCustomService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllocatCustomService/RegisterCustomerAndChargeProfile", ReplyAction="http://tempuri.org/AllocatCustomService/RegisterCustomerAndChargeProfileResponse")]
        Allocat.WebApi.CustomService.ResCreateCustomerProfile RegisterCustomerAndChargeProfile(Allocat.WebApi.CustomService.Customer objCustomer, decimal AmountToBeCharged);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllocatCustomService/RegisterCustomerAndChargeProfile", ReplyAction="http://tempuri.org/AllocatCustomService/RegisterCustomerAndChargeProfileResponse")]
        System.Threading.Tasks.Task<Allocat.WebApi.CustomService.ResCreateCustomerProfile> RegisterCustomerAndChargeProfileAsync(Allocat.WebApi.CustomService.Customer objCustomer, decimal AmountToBeCharged);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllocatCustomService/CreateCustomerPaymentProfile", ReplyAction="http://tempuri.org/AllocatCustomService/CreateCustomerPaymentProfileResponse")]
        string CreateCustomerPaymentProfile(string ApiLoginID, string ApiTransactionKey, Allocat.WebApi.CustomService.Customer objCustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllocatCustomService/CreateCustomerPaymentProfile", ReplyAction="http://tempuri.org/AllocatCustomService/CreateCustomerPaymentProfileResponse")]
        System.Threading.Tasks.Task<string> CreateCustomerPaymentProfileAsync(string ApiLoginID, string ApiTransactionKey, Allocat.WebApi.CustomService.Customer objCustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllocatCustomService/GetCustomerProfile", ReplyAction="http://tempuri.org/AllocatCustomService/GetCustomerProfileResponse")]
        void GetCustomerProfile(string ApiLoginID, string ApiTransactionKey, string customerProfileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllocatCustomService/GetCustomerProfile", ReplyAction="http://tempuri.org/AllocatCustomService/GetCustomerProfileResponse")]
        System.Threading.Tasks.Task GetCustomerProfileAsync(string ApiLoginID, string ApiTransactionKey, string customerProfileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllocatCustomService/UpdateCustomerProfile", ReplyAction="http://tempuri.org/AllocatCustomService/UpdateCustomerProfileResponse")]
        void UpdateCustomerProfile(string ApiLoginID, string ApiTransactionKey, string customerProfileId, string merchantCustomerId, string description, string newEmailId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllocatCustomService/UpdateCustomerProfile", ReplyAction="http://tempuri.org/AllocatCustomService/UpdateCustomerProfileResponse")]
        System.Threading.Tasks.Task UpdateCustomerProfileAsync(string ApiLoginID, string ApiTransactionKey, string customerProfileId, string merchantCustomerId, string description, string newEmailId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AllocatCustomServiceChannel : Allocat.WebApi.CustomService.AllocatCustomService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AllocatCustomServiceClient : System.ServiceModel.ClientBase<Allocat.WebApi.CustomService.AllocatCustomService>, Allocat.WebApi.CustomService.AllocatCustomService {
        
        public AllocatCustomServiceClient() {
        }
        
        public AllocatCustomServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AllocatCustomServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllocatCustomServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllocatCustomServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Allocat.WebApi.CustomService.ResCreateCustomerProfile RegisterCustomerAndChargeProfile(Allocat.WebApi.CustomService.Customer objCustomer, decimal AmountToBeCharged) {
            return base.Channel.RegisterCustomerAndChargeProfile(objCustomer, AmountToBeCharged);
        }
        
        public System.Threading.Tasks.Task<Allocat.WebApi.CustomService.ResCreateCustomerProfile> RegisterCustomerAndChargeProfileAsync(Allocat.WebApi.CustomService.Customer objCustomer, decimal AmountToBeCharged) {
            return base.Channel.RegisterCustomerAndChargeProfileAsync(objCustomer, AmountToBeCharged);
        }
        
        public string CreateCustomerPaymentProfile(string ApiLoginID, string ApiTransactionKey, Allocat.WebApi.CustomService.Customer objCustomer) {
            return base.Channel.CreateCustomerPaymentProfile(ApiLoginID, ApiTransactionKey, objCustomer);
        }
        
        public System.Threading.Tasks.Task<string> CreateCustomerPaymentProfileAsync(string ApiLoginID, string ApiTransactionKey, Allocat.WebApi.CustomService.Customer objCustomer) {
            return base.Channel.CreateCustomerPaymentProfileAsync(ApiLoginID, ApiTransactionKey, objCustomer);
        }
        
        public void GetCustomerProfile(string ApiLoginID, string ApiTransactionKey, string customerProfileId) {
            base.Channel.GetCustomerProfile(ApiLoginID, ApiTransactionKey, customerProfileId);
        }
        
        public System.Threading.Tasks.Task GetCustomerProfileAsync(string ApiLoginID, string ApiTransactionKey, string customerProfileId) {
            return base.Channel.GetCustomerProfileAsync(ApiLoginID, ApiTransactionKey, customerProfileId);
        }
        
        public void UpdateCustomerProfile(string ApiLoginID, string ApiTransactionKey, string customerProfileId, string merchantCustomerId, string description, string newEmailId) {
            base.Channel.UpdateCustomerProfile(ApiLoginID, ApiTransactionKey, customerProfileId, merchantCustomerId, description, newEmailId);
        }
        
        public System.Threading.Tasks.Task UpdateCustomerProfileAsync(string ApiLoginID, string ApiTransactionKey, string customerProfileId, string merchantCustomerId, string description, string newEmailId) {
            return base.Channel.UpdateCustomerProfileAsync(ApiLoginID, ApiTransactionKey, customerProfileId, merchantCustomerId, description, newEmailId);
        }
    }
}
